-- ============================================================
-- 05_data_validation.sql  |  Tahap 6 — Data Validation
-- ============================================================
-- GRAIN:       TODO (1 baris = 1 order / item / payment / review / ...)
-- POPULATION:  TODO (sebutkan flag, mis. is_revenue_order = TRUE)
-- DENOMINATOR: TODO (untuk metrik rate/persentase, sebutkan populasi + n)
-- ============================================================
-- Cara jalankan (DuckDB CLI):  .read sql/05_data_validation.sql
-- Pendamping wajib:            docs/05_data_validation.md
--   (Input · Proses Analisis · Temuan · Output · Assumptions · Batasan data · Kesimpulan)
-- Aturan: Fan-out Guard — pre-aggregate tabel anak ke grain order_id sebelum join,
--         sertakan reconciliation check setelah join.
-- ============================================================

-- TODO: analytical populations, flags, KPI Lock, fan-out test
